apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: portfolio
spec:
  template:
    spec:
      containers:
        - image: debasishbsws/debasishbsws-portfolio:e471ed6
          ports:
            - containerPort: 3000
