apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: portfolio
spec:
  template:
    spec:
      containers:
        - image: debasishbsws/debasish-portfolio
          ports:
            - containerPort: 3000
