apiVersion: v1
kind: Service
metadata:
  name: node-portfolio-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-portfolio-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000