name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Github Login 
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.G_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag debasishbsws/debasishbsws-portfolio:$(git rev-parse --short "$GITHUB_SHA") --tag debasishbsws/debasishbsws-portfolio:latest

    - name: Push specific tag image to DockerHub
      run: docker push debasishbsws/debasishbsws-portfolio:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the latest tag Docker image to DockerHub
      run: docker push debasishbsws/debasishbsws-portfolio:latest

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
        token: ${{ secrets.G_TOKEN }}
      
    - name: Update manifest
      if: ${{ github.actor != 'update-manifest-bot' }}
      run: |
        git config --global user.name "update-manifest-bot"
        git config --global user.email "bot.debasishbsws@gmail.com"
        echo echo ${{ github.sha }}
        sed -i "s#${{ github.actor }}.*#${{ github.actor }}/debasishbsws-portfolio:$(git rev-parse --short "$GITHUB_SHA")#g" ops/knative-serving.yaml
        git add -A
        git commit -am "Update manifest with $GITHUB_SHA"

    - run: echo ${{ github }}
    - run: git push origin master
          

